/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model2(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/_Buggy Guy.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 4.8, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Buggy_guy_1.geometry}
          material={materials.StandardCACACA}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Buggy_guy_2.geometry}
          material={materials.Standard787878}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Buggy_guy_3.geometry}
          material={materials.Standard7884E7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Buggy_guy_4.geometry}
          material={materials.Standard4CA87C}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/_Buggy Guy.gltf");

